CREATE DATABASE login_register_sys CHARACTER SET UTF8MB4;
USE login_register_sys;

CREATE TABLE users (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
username VARCHAR(20) NOT NULL UNIQUE,
pass VARCHAR(30) NOT NULL
);